version: '3.8'

services:
  traefik:
    image: traefik:v2.6
    restart: always
    command:
      # Enable Dashboard
      - "--api.insecure=true"
      - "--api.dashboard=true"
      # Dokcer configuration
      - "--providers.docker"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.docker.network=traefik_web"
      # Configure entrypoint
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      # HTTP -> HTTPS
      - "--entrypoints.http.http.redirections.entrypoint.to=https"
      - "--entrypoints.http.http.redirections.entrypoint.scheme=https"
      # Configure certificate
      - "--entrypoints.https.http.tls.certResolver=le"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
      - "--certificatesresolvers.le.acme.email=oeztirak-yunus1516@hotmail.com"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    networks:
      - traefik_web

  frontend:
    image: nginx:1.20
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`invoicer.at`)"
    networks:
      - traefik_web

  backend:
    environment:
      - DB_CONNECTION_STRING=Server=dbserver,1433;Database=BillingSoftwareDb;User Id=sa;Password=BillingSoftware20222022!
    build: ./BillingSoftwareBackend/.
    links:
      - dbserver
    depends_on:
      - dbserver
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`backend.invoicer.at`)"
    networks:
      - traefik_web 

  dbserver:
    image: mcr.microsoft.com/mssql/server:2019-latest 
    environment:  
      ACCEPT_EULA: "Y"  
      SA_PASSWORD: "BillingSoftware20222022!"
    volumes:  
      - mssqlsystem:/var/opt/mssql/ 
      - mssqluser:/var/opt/sqlserver
    networks:
      - traefik_web    

volumes:
  mssqlsystem: 
  mssqluser:

networks:
  traefik_web:
    name: traefik_web
    driver: bridge
    ipam:
      config:
        - subnet: 10.8.0.0/16