export * from './addresses.service';
import { AddressesService } from './addresses.service';
export * from './auth.service';
import { AuthService } from './auth.service';
export * from './bankInformations.service';
import { BankInformationsService } from './bankInformations.service';
export * from './companies.service';
import { CompaniesService } from './companies.service';
export * from './contacts.service';
import { ContactsService } from './contacts.service';
export * from './deliveryNotes.service';
import { DeliveryNotesService } from './deliveryNotes.service';
export * from './documentInformations.service';
import { DocumentInformationsService } from './documentInformations.service';
export * from './files.service';
import { FilesService } from './files.service';
export * from './invoices.service';
import { InvoicesService } from './invoices.service';
export * from './offers.service';
import { OffersService } from './offers.service';
export * from './orderConfirmations.service';
import { OrderConfirmationsService } from './orderConfirmations.service';
export * from './positions.service';
import { PositionsService } from './positions.service';
export * from './products.service';
import { ProductsService } from './products.service';
export * from './users.service';
import { UsersService } from './users.service';
export const APIS = [AddressesService, AuthService, BankInformationsService, CompaniesService, ContactsService, DeliveryNotesService, DocumentInformationsService, FilesService, InvoicesService, OffersService, OrderConfirmationsService, PositionsService, ProductsService, UsersService];
