/**
 * BillingSoftware.Web
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { DocumentInformations } from '../model/documentInformations';
import { PositionDto } from '../model/positionDto';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class DocumentInformationsService {

    protected basePath = '/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param documentInformationId 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiDocumentInformationsAddPositionDocumentInformationIdPut(documentInformationId: string, body?: PositionDto, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public apiDocumentInformationsAddPositionDocumentInformationIdPut(documentInformationId: string, body?: PositionDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public apiDocumentInformationsAddPositionDocumentInformationIdPut(documentInformationId: string, body?: PositionDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public apiDocumentInformationsAddPositionDocumentInformationIdPut(documentInformationId: string, body?: PositionDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (documentInformationId === null || documentInformationId === undefined) {
            throw new Error('Required parameter documentInformationId was null or undefined when calling apiDocumentInformationsAddPositionDocumentInformationIdPut.');
        }


        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<any>('put',`${this.basePath}/api/DocumentInformations/add-position/${encodeURIComponent(String(documentInformationId))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param documentInformationId 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiDocumentInformationsAddPositionsDocumentInformationIdPut(documentInformationId: string, body?: Array<PositionDto>, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public apiDocumentInformationsAddPositionsDocumentInformationIdPut(documentInformationId: string, body?: Array<PositionDto>, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public apiDocumentInformationsAddPositionsDocumentInformationIdPut(documentInformationId: string, body?: Array<PositionDto>, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public apiDocumentInformationsAddPositionsDocumentInformationIdPut(documentInformationId: string, body?: Array<PositionDto>, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (documentInformationId === null || documentInformationId === undefined) {
            throw new Error('Required parameter documentInformationId was null or undefined when calling apiDocumentInformationsAddPositionsDocumentInformationIdPut.');
        }


        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<any>('put',`${this.basePath}/api/DocumentInformations/add-positions/${encodeURIComponent(String(documentInformationId))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param documentInformationId 
     * @param positionId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiDocumentInformationsDeletePositionDocumentInformationIdPositionIdPut(documentInformationId: string, positionId: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public apiDocumentInformationsDeletePositionDocumentInformationIdPositionIdPut(documentInformationId: string, positionId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public apiDocumentInformationsDeletePositionDocumentInformationIdPositionIdPut(documentInformationId: string, positionId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public apiDocumentInformationsDeletePositionDocumentInformationIdPositionIdPut(documentInformationId: string, positionId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (documentInformationId === null || documentInformationId === undefined) {
            throw new Error('Required parameter documentInformationId was null or undefined when calling apiDocumentInformationsDeletePositionDocumentInformationIdPositionIdPut.');
        }

        if (positionId === null || positionId === undefined) {
            throw new Error('Required parameter positionId was null or undefined when calling apiDocumentInformationsDeletePositionDocumentInformationIdPositionIdPut.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('put',`${this.basePath}/api/DocumentInformations/delete-position/${encodeURIComponent(String(documentInformationId))}/${encodeURIComponent(String(positionId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiDocumentInformationsGet(observe?: 'body', reportProgress?: boolean): Observable<Array<DocumentInformations>>;
    public apiDocumentInformationsGet(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<DocumentInformations>>>;
    public apiDocumentInformationsGet(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<DocumentInformations>>>;
    public apiDocumentInformationsGet(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<DocumentInformations>>('get',`${this.basePath}/api/DocumentInformations`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiDocumentInformationsIdGet(id: string, observe?: 'body', reportProgress?: boolean): Observable<DocumentInformations>;
    public apiDocumentInformationsIdGet(id: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DocumentInformations>>;
    public apiDocumentInformationsIdGet(id: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DocumentInformations>>;
    public apiDocumentInformationsIdGet(id: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling apiDocumentInformationsIdGet.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<DocumentInformations>('get',`${this.basePath}/api/DocumentInformations/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiDocumentInformationsPut(body?: DocumentInformations, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public apiDocumentInformationsPut(body?: DocumentInformations, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public apiDocumentInformationsPut(body?: DocumentInformations, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public apiDocumentInformationsPut(body?: DocumentInformations, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<any>('put',`${this.basePath}/api/DocumentInformations`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
