/**
 * BillingSoftware.Web
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Address } from './address';
import { BSFile } from './bSFile';
import { BankInformation } from './bankInformation';
import { CompanyDocumentCounter } from './companyDocumentCounter';
import { Contact } from './contact';
import { DeliveryNote } from './deliveryNote';
import { Invoice } from './invoice';
import { Offer } from './offer';
import { OrderConfirmation } from './orderConfirmation';
import { Product } from './product';
import { User } from './user';

export interface Company { 
    companyName: string;
    email: string;
    phoneNumber: string;
    ustNumber?: string;
    addressId?: string;
    bankInformationId?: string;
    companyDocumentCounter?: CompanyDocumentCounter;
    bankInformation?: BankInformation;
    address?: Address;
    users?: Array<User>;
    contacts?: Array<Contact>;
    offers?: Array<Offer>;
    orderConfirmations?: Array<OrderConfirmation>;
    deliveryNotes?: Array<DeliveryNote>;
    invoices?: Array<Invoice>;
    products?: Array<Product>;
    files?: Array<BSFile>;
    id?: string;
    rowVersion?: string;
}