/**
 * BillingSoftware.Web
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DocumentInformations } from './documentInformations';
import { Product } from './product';
import { TypeOfDiscount } from './typeOfDiscount';

export interface Position { 
    quantity: number;
    discount?: number;
    typeOfDiscount?: TypeOfDiscount;
    readonly totalPriceNet?: number;
    readonly productPriceNet?: number;
    productId: string;
    documentInformationId?: string;
    product?: Product;
    documentInformation?: DocumentInformations;
    id?: string;
    rowVersion?: string;
}