/**
 * BillingSoftware.Web
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type TypeOfContact = 'Supplier' | 'Client' | 'Partner' | 'ProspectiveClient' | 'NoTargetGroup';

export const TypeOfContact = {
    Supplier: 'Supplier' as TypeOfContact,
    Client: 'Client' as TypeOfContact,
    Partner: 'Partner' as TypeOfContact,
    ProspectiveClient: 'ProspectiveClient' as TypeOfContact,
    NoTargetGroup: 'NoTargetGroup' as TypeOfContact
};