/**
 * BillingSoftware.Web
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type Unit = 'Stück' | 'Quadratmeter' | 'Meter' | 'Kilogramm' | 'Tonnen' | 'Pauschal' | 'Kubikmeter' | 'Stunden' | 'Kilometer' | 'Prozent' | 'Tage' | 'Liter';

export const Unit = {
    Stck: 'Stück' as Unit,
    Quadratmeter: 'Quadratmeter' as Unit,
    Meter: 'Meter' as Unit,
    Kilogramm: 'Kilogramm' as Unit,
    Tonnen: 'Tonnen' as Unit,
    Pauschal: 'Pauschal' as Unit,
    Kubikmeter: 'Kubikmeter' as Unit,
    Stunden: 'Stunden' as Unit,
    Kilometer: 'Kilometer' as Unit,
    Prozent: 'Prozent' as Unit,
    Tage: 'Tage' as Unit,
    Liter: 'Liter' as Unit
};